name: Check Hugo Site

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-mail --accept 200,429 --timeout 30s public

      - name: Check for missing images
        run: |
          missing=0
          for img in $(find public -type f -name '*.html' -exec grep -oE 'src="[^"]+"' {} \; | sed 's/src="//' | sed 's/"//'); do
            if [[ "$img" =~ ^http ]]; then continue; fi
            if [ ! -f "public/$img" ] && [ ! -f "public${img}" ]; then
              echo "Missing image: $img"; missing=1
            fi
          done
          exit $missing

      - name: Lint CSS (optional)
        run: |
          npm install -g stylelint stylelint-config-standard
          # Exclude Quartz-generated notes CSS files
          if compgen -G "public/**/*.css" > /dev/null; then
            find public -name "*.css" -not -path "public/notes/*" | xargs -r stylelint || echo "No CSS files to lint or linting skipped"
          fi
